server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vtb?useSSL=false&amp;serverTimezone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: "/docs"