server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_data?useSSL=false&amp;serverTimezone=UTC
    username: postgres
    password: admin123
    driver-class-name: org.postgresql.Driver






