CREATE TABLE atms
(
    atm_id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address   VARCHAR(255),
    bnkcd     VARCHAR(255),
    code      VARCHAR(255),
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    all_day   BOOLEAN,
    CONSTRAINT pk_atms PRIMARY KEY (atm_id)
);

CREATE TABLE office
(
    office_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    address     VARCHAR(255),
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    city        VARCHAR(255),
    postal_code VARCHAR(255),
    filters_id  INTEGER,
    status_id   INTEGER,
    CONSTRAINT pk_office PRIMARY KEY (office_id)
);

CREATE TABLE office_filters
(
    filters_id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ramp_having         BOOLEAN,
    cash_return         BOOLEAN,
    pickup_locations    BOOLEAN,
    retail_auto_lending BOOLEAN,
    CONSTRAINT pk_office_filters PRIMARY KEY (filters_id)
);

CREATE TABLE status
(
    status_id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    CONSTRAINT pk_status PRIMARY KEY (status_id)
);

ALTER TABLE office
    ADD CONSTRAINT FK_OFFICE_ON_FILTERS FOREIGN KEY (filters_id) REFERENCES office_filters (filters_id);

ALTER TABLE office
    ADD CONSTRAINT FK_OFFICE_ON_STATUS FOREIGN KEY (status_id) REFERENCES status (status_id);